Homework2
romanticist77/KamranAkhmedov_LevelUp pull request #4
Opened 2023-05-30 22:16 UTC by romanticist77

2023-06-05 10:04 UTC, khda91 requested changes
Не хватает негативных проверок

2023-06-05 10:04 UTC, khda91 commented on src/main/java/ru/levelup/at/homework2/TicketNumberChecker.java
> +    public boolean checkTicketNumber(String ticketNumber) {
А что будет если на вход подам 

- null
- empty string
- some string

2023-06-10 13:38 UTC, romanticist77 commented on src/main/java/ru/levelup/at/homework2/TicketNumberChecker.java
> +    public boolean checkTicketNumber(String ticketNumber) {
Добавлены новые негативные кейсы

2023-06-11 17:03 UTC, khda91 requested changes
исправить комментрарии

2023-06-11 17:03 UTC, khda91 commented on src/main/java/ru/levelup/at/homework2/TicketNumberChecker.java
> +            throw new NullPointerException("Illegal argument is provided");
`NullPointerException` плохое тут решение. Это исключение выбрасывается обычно когда какой-то метод вызывается у **null** объекта. 
Тут лучше полдойдёт `IllegalArgumentException`

2023-06-11 17:03 UTC, khda91 commented on src/test/java/ru/levelup/at/homework2/NegativeTicketNumberCheckerTest.java
> +    public void checkerNegativeTest(String ticketNumber) {
На лекции было показако как правильно пичсать итесты на ислючения, которые могут быть выброшены

2023-06-11 18:38 UTC, romanticist77 commented on src/main/java/ru/levelup/at/homework2/TicketNumberChecker.java
> +            throw new NullPointerException("Illegal argument is provided");
Изменил ошибку на IllegalArgumentException

2023-06-11 18:38 UTC, romanticist77 commented on src/test/java/ru/levelup/at/homework2/NegativeTicketNumberCheckerTest.java
> +    public void checkerNegativeTest(String ticketNumber) {
Добавил ожидаемые исключения и сообщения об ошибке

2023-06-26 08:40 UTC, khda91 approved these changes
Работа принята

2023-07-02 11:42 UTC, merged