Homework3
romanticist77/KamranAkhmedov_LevelUp pull request #5
Opened 2023-06-12 16:19 UTC by romanticist77

2023-06-19 20:58 UTC, khda91 requested changes
Исправь, пожалуйста, комментарии

2023-06-19 20:58 UTC, khda91 commented on src/test/java/ru/levelup/at/homework3/CustomRulesTest.java
> +    public void setUp() {
Почему бы не вынести before и after методы в базовый класс для тестов?

2023-06-19 20:58 UTC, khda91 commented on src/test/java/ru/levelup/at/homework3/CustomRulesTest.java
> +            ExpectedConditions.visibilityOfElementLocated(By.xpath("//button[contains(@class, 'ph-login')]")));
У тебя в коде используются как явные, так и неявные ожидания. Они накладываются друг на друга. 
Нужно выбрать одно из них или выключать неявные ожидания перед тем, как использовать явные.

2023-06-19 20:58 UTC, khda91 commented on src/test/java/ru/levelup/at/homework3/EntryTest.java
> +public class EntryTest {
Есть аналогичные комментарии классу src/test/java/ru/levelup/at/homework3/CustomRulesTest.java

2023-06-19 20:58 UTC, khda91 commented on src/test/java/ru/levelup/at/homework3/IncomingToTrashBinTest.java
> +public class IncomingToTrashBinTest {
Есть аналогичные комментарии классу src/test/java/ru/levelup/at/homework3/CustomRulesTest.java

2023-07-02 12:19 UTC, romanticist77 commented on src/test/java/ru/levelup/at/homework3/CustomRulesTest.java
> +    public void setUp() {
Исправил

2023-07-02 12:19 UTC, romanticist77 commented on src/test/java/ru/levelup/at/homework3/CustomRulesTest.java
> +            ExpectedConditions.visibilityOfElementLocated(By.xpath("//button[contains(@class, 'ph-login')]")));
Исправил

2023-07-02 12:19 UTC, romanticist77 commented on src/test/java/ru/levelup/at/homework3/EntryTest.java
> +public class EntryTest {
Исправил

2023-07-02 12:19 UTC, romanticist77 commented on src/test/java/ru/levelup/at/homework3/IncomingToTrashBinTest.java
> +public class IncomingToTrashBinTest {
Исправил

2023-07-13 17:32 UTC, merged